/**
 * @fileoverview Shared COSE message inspection helpers (pretty core).
 *
 * Extracted from the COSE_Sign1 formatter so all COSE message type formatters
 * (Sign1, Sign, Encrypt0, Encrypt, Mac0, Mac) can reuse common logic:
 * - Protected header decoding
 * - Content type extraction
 * - Payload inspection
 * - Sub-formatter delegation & contribution merging
 */
import * as cbor from 'cbor';
import { createHash } from 'crypto';
import type { PrettyFormatterContext } from '../registry';
import type {
    CoseHeaders,
    HeaderInfo,
    PayloadInfo,
    SignatureInfo
} from '../extenders/coseSign1/coseSign1InspectionTypes';
import { toInt32 } from './numeric';
import { asCborMap, isLikelyUtf8Text, toBuffer } from '../util';
import { buildCoseHeadersMap, mergeHeaderContributions } from '../extenders/coseSign1/coseHeaders';

/**
 * Unwrap a CBOR tag from a value, returning the inner value if the tag matches.
 */
export function unwrapCoseTag(value: unknown, expectedTag: number): unknown | null {
    if (value instanceof (cbor as any).Tagged) {
        const tag = (value as any).tag;
        const inner = (value as any).value;
        if (tag === expectedTag) {
            return inner;
        }
    }
    return null;
}

/**
 * Decode CBOR-encoded protected headers into a Map.
 */
export function decodeProtectedHeaders(protectedBytes: Buffer | null): Map<unknown, unknown> {
    if (!protectedBytes || protectedBytes.length === 0) {
        return new Map();
    }
    try {
        const decoded = cbor.decodeFirstSync(protectedBytes);
        return asCborMap(decoded) ?? new Map();
    } catch {
        return new Map();
    }
}

/**
 * Extract content type string from a COSE header map (label 3).
 */
export function getContentTypeString(headers: Map<unknown, unknown>): string | undefined {
    const contentType = headers.get(3);
    if (typeof contentType === 'string') {
        return contentType;
    }
    const ctInt = toInt32(contentType);
    return ctInt === null ? undefined : ctInt.toString();
}

/**
 * Build a PayloadInfo inspection model from a COSE payload.
 */
export function buildPayloadInfo(ctx: PrettyFormatterContext, payload: unknown, contentType?: string): PayloadInfo {
    const payloadBytes = toBuffer(payload);
    const isEmbedded = !!(payloadBytes && payloadBytes.length > 0);

    const info: PayloadInfo = { isEmbedded };
    if (contentType) {
        info.contentType = contentType;
    }

    if (!isEmbedded || !payloadBytes) {
        return info;
    }

    info.sizeBytes = payloadBytes.length;
    info.isText = isLikelyUtf8Text(payloadBytes);

    const preview = ctx.bytesPreview(payloadBytes) as any;
    if (preview && preview._type === 'bytes') {
        info.bytes = preview;
    }

    if (info.isText) {
        // Text previews are generated by the preview generator based on `_previewHints`.
    } else {
        info.sha256 = createHash('sha256').update(payloadBytes).digest('hex').toUpperCase();

        // Decode embedded CBOR/COSE for reasonable sizes.
        if (payloadBytes.length <= 1024 * 1024) {
            const decoded = ctx.tryDecodeEmbedded(payloadBytes, 0);
            if (decoded !== undefined) {
                info.decoded = ctx.format(decoded, 1);
            }
        }
    }

    return info;
}

/**
 * Build a SignatureInfo/TagInfo model (just wraps totalSizeBytes).
 */
export function buildSignatureInfo(totalSizeBytes: number): SignatureInfo {
    return { totalSizeBytes };
}

/**
 * Estimate the total byte size of a COSE message value.
 */
export function estimateTotalSizeBytes(value: unknown, ctx: PrettyFormatterContext): number {
    if (typeof ctx.totalSizeBytes === 'number' && ctx.totalSizeBytes > 0) {
        return ctx.totalSizeBytes;
    }
    if (value instanceof (cbor as any).Tagged) {
        try {
            const encoded = cbor.encodeOne(value as any);
            const buf = Buffer.isBuffer(encoded) ? encoded : Buffer.from(encoded);
            return buf.length;
        } catch {
            return 0;
        }
    }
    return 0;
}

/** Delegation target types for sub-formatter dispatch. */
type DelegationType = 'cose-alg' | 'cose-certificates' | 'cose-hash-message' | 'cose-countersignature';

const ALL_DELEGATIONS: DelegationType[] = [
    'cose-certificates',
    'cose-hash-message',
    'cose-countersignature',
    'cose-alg'
];

/**
 * Delegate to sub-formatters (algorithm, certificates, hash-message, countersigs)
 * and merge their header contributions back into the provided header objects.
 */
export function delegateAndMergeHeaders(
    ctx: PrettyFormatterContext,
    protectedMap: Map<unknown, unknown>,
    unprotectedMap: Map<unknown, unknown> | null,
    protectedHeaders: CoseHeaders,
    unprotectedHeaders: CoseHeaders
): void {
    for (const delegation of ALL_DELEGATIONS) {
        const ext = ctx.format(
            {
                _type: delegation,
                protectedHeaders: protectedMap,
                unprotectedHeaders: unprotectedMap
            },
            ctx.depth + 1
        ) as any;

        if (ext && typeof ext === 'object') {
            if (ext.protectedHeaders && typeof ext.protectedHeaders === 'object') {
                mergeHeaderContributions(protectedHeaders, ext.protectedHeaders as Record<string, Partial<HeaderInfo>>);
            }
            if (ext.unprotectedHeaders && typeof ext.unprotectedHeaders === 'object') {
                mergeHeaderContributions(unprotectedHeaders, ext.unprotectedHeaders as Record<string, Partial<HeaderInfo>>);
            }
        }
    }
}

/**
 * Strip empty header objects from a result for cleaner output.
 */
export function cleanEmptyHeaders(result: { protectedHeaders?: CoseHeaders; unprotectedHeaders?: CoseHeaders }): void {
    if (!result.unprotectedHeaders || Object.keys(result.unprotectedHeaders).length === 0) {
        delete result.unprotectedHeaders;
    }
    if (result.protectedHeaders && Object.keys(result.protectedHeaders).length === 0) {
        delete result.protectedHeaders;
    }
}

// Re-export for convenience
export { buildCoseHeadersMap, mergeHeaderContributions };
